const levels = [
    { grid: [[0, 2, 0, 4, 2], [0, 1, 1, 1, 0], [0, 0, 5, 0, 0], [0, 1, 1, 1, 0], [0, 2, 4, 2, 0]], start: { x: 0, y: 0, dir: 0 }, questions: [{ q: "Qual operador retorna 'true' se AMBAS as condições forem verdadeiras?", a: ["OR", "AND", "NOT"], c: 1 }, { q: "Uma estrutura 'se/então' é um...?", a: ["Loop", "Variável", "Condicional"], c: 2 }] },
    { grid: [[4, 0, 1, 0, 2], [0, 0, 1, 0, 0], [2, 0, 4, 0, 5], [0, 0, 1, 0, 1], [0, 0, 2, 0, 4]], start: { x: 0, y: 2, dir: 0 }, questions: [{ q: "Qual o resultado de: (true AND false)?", a: ["true", "false", "error"], c: 1 }, { q: "O que um loop 'while' faz?", a: ["Executa uma vez", "Executa se falso", "Repete enquanto verdadeiro"], c: 2 }, { q: "Em binário, como se representa o número 2?", a: ["11", "01", "10"], c: 2 }] },
    { grid: [[0, 0, 2, 0, 5], [0, 1, 4, 1, 0], [2, 0, 0, 0, 2], [0, 1, 4, 1, 0], [0, 0, 2, 0, 0]], start: { x: 0, y: 2, dir: 0 }, questions: [{ q: "Qual o tipo de dado para '123'?", a: ["String", "Integer", "Boolean"], c: 0 }, { q: "Qual o tipo de dado para 'Olá Mundo'?", a: ["String", "Integer", "Boolean"], c: 0 }] },
    { grid: [[2, 0, 0, 0, 2], [0, 1, 1, 1, 0], [4, 0, 5, 0, 4], [0, 1, 1, 1, 0], [2, 0, 0, 0, 2]], start: { x: 0, y: 0, dir: 1 }, questions: [{ q: "O que um array armazena?", a: ["Um único valor", "Múltiplos valores", "Nada"], c: 1 }, { q: "O índice de um array geralmente começa em qual número?", a: ["1", "0", "-1"], c: 1 }] },
    { grid: [[0, 0, 4, 0, 0], [0, 1, 2, 1, 0], [2, 0, 5, 0, 2], [0, 1, 4, 1, 0], [0, 4, 2, 0, 0]], start: { x: 2, y: 3, dir: 0 }, questions: [{ q: "O que é uma função?", a: ["Um tipo de dado", "Um bloco de código reutilizável", "Uma variável"], c: 1 }, { q: "O que 'return' faz em uma função?", a: ["Imprime um valor", "Encerra a função e envia um valor de volta", "Cria um loop"], c: 1 }, { q: "O que é um loop infinito?", a: ["Um loop que nunca termina", "Um loop muito rápido", "Um erro de sintaxe"], c: 0 }] },
    { grid: [[2, 0, 4, 0, 2], [0, 1, 1, 1, 0], [0, 0, 5, 0, 0], [0, 1, 4, 1, 0], [2, 4, 0, 0, 2]], start: { x: 2, y: 2, dir: 0 }, questions: [{ q: "Qual operador é usado para atribuição de valor?", a: ["=", "==", "==="], c: 0 }, { q: "O que é uma variável?", a: ["Um valor fixo", "Um nome para um local de armazenamento", "Uma função"], c: 1 }, { q: "Qual o operador para 'maior ou igual a'?", a: [">", "=>", ">="], c: 2 }] },
    { grid: [[0, 2, 0, 2, 0], [0, 1, 4, 1, 0], [5, 0, 0, 0, 0], [0, 1, 4, 1, 0], [0, 2, 0, 2, 0]], start: { x: 2, y: 2, dir: 3 }, questions: [{ q: "Como se declara uma variável para armazenar um nome (texto) no Portugol?", a: ["inteiro nome", "cadeia nome", "real nome"], c: 1 }, { q: "Qual das alternativas é uma proposição (tem valor verdadeiro ou falso)?", a: ["Abra a porta!", "2 + 2 = 4", "Bom dia"], c: 1 }] },
    { grid: [[2, 0, 1, 0, 5], [4, 0, 1, 0, 0], [0, 0, 1, 0, 2], [0, 0, 0, 0, 0], [2, 4, 0, 1, 0]], start: { x: 2, y: 3, dir: 0 }, questions: [{ q: "Em um fluxograma, o que a forma de losango representa?", a: ["Início/Fim", "Processo", "Uma decisão"], c: 2 }, { q: "O que é 'pseudocódigo'?", a: ["Um código com erros", "Uma descrição do algoritmo", "Um código secreto"], c: 1 }] },
    { grid: [[0, 0, 2, 0, 0], [0, 1, 4, 1, 0], [2, 4, 0, 4, 2], [0, 1, 0, 1, 0], [5, 0, 0, 0, 0]], start: { x: 2, y: 2, dir: 2 }, questions: [{ q: "Qual comando é usado para exibir uma mensagem na tela no Portugol?", a: ["leia()", "escreva()", "imprima()"], c: 1 }, { q: "O que é um algoritmo?", a: ["Um erro de software", "Uma sequência de passos para resolver um problema", "Uma linguagem de programação"], c: 1 }, { q: "O que é 'compilação'?", a: ["Executar o código", "Traduzir para código de máquina", "Escrever o código"], c: 1 }] },
    { grid: [[4, 0, 0, 0, 4], [0, 1, 1, 1, 0], [2, 0, 2, 0, 2], [0, 0, 5, 0, 0], [0, 0, 0, 0, 0]], start: { x: 0, y: 4, dir: 0 }, questions: [{ q: "O que '&&' representa em lógica booleana?", a: ["OR", "NOT", "AND"], c: 2 }, { q: "Qual o operador lógico para 'OU'?", a: ["&&", "||", "!!"], c: 1 }] },
    { grid: [[2, 1, 0, 1, 2], [0, 4, 0, 4, 0], [0, 0, 5, 0, 0], [0, 2, 0, 2, 0], [0, 0, 0, 0, 0]], start: { x: 2, y: 4, dir: 0 }, questions: [{ q: "Qual o valor booleano para 'falso'?", a: ["true", "false", "null"], c: 1 }, { q: "O que o tipo de dado 'booleano' armazena?", a: ["Números", "Texto", "Verdadeiro ou Falso"], c: 2 }] },
    { grid: [[0, 0, 2, 4, 0], [1, 0, 0, 0, 1], [2, 0, 5, 0, 2], [1, 0, 4, 0, 1], [0, 0, 2, 0, 0]], start: { x: 2, y: 2, dir: 3 }, questions: [{ q: "O que é 'sintaxe' em programação?", a: ["As regras de escrita da linguagem", "A lógica do programa", "O resultado final"], c: 0 }, { q: "O que é um 'parâmetro' de uma função?", a: ["O valor de retorno", "Uma variável local", "Um valor de entrada"], c: 2 }] },
    // ... resto do código continua igual (sem alterações nas demais perguntas)
].map(level => { 
    if (level.questions) { 
        level.questions = level.questions.map(q => ({ question: q.q, answers: q.a, correct: q.c })); 
    } 
    return level; 
});
